[supabase]
url = "https://aeytxfekleefifghbryf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFleXR4ZmVrbGVlZmlmZ2hicnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTQ5ODIsImV4cCI6MjA2NzQ5MDk4Mn0.NWCCwRNagZI5Ju_mhMiLV3cQTAm6PJIkmqfm9Ur1860"

[env]
GEMINI_API_KEY = "AIzaSyDfZI075-CL3kU_kTolKqDMR5H_9CTq2Cc"
